name: Docker Build and Push

on:
  workflow_dispatch:
  push:
    paths:
      - 'Dockerfile'
      - 'requirements.txt'

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
          ref: ${{ github.head_ref }}

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    - id: repo_name
      uses: ASzc/change-string-case-action@v6
      with:
        string: ${{ github.event.repository.name }}

    - name: Build and export to Docker
      uses: docker/build-push-action@v6
      with:
        load: true
        tags: "${{ secrets.DOCKERHUB_USERNAME }}/${{ steps.repo_name.outputs.lowercase }}:${{ github.ref_name }}"
        build-args: |
          GITHUB_TOKEN=${{ secrets.GH_TOKEN }}
    
    - name: Test Image
      run: |
        docker run --rm "${{ secrets.DOCKERHUB_USERNAME }}/${{ steps.repo_name.outputs.lowercase }}:${{ github.ref_name }}"

    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        push: true
        tags: "${{ secrets.DOCKERHUB_USERNAME }}/${{ steps.repo_name.outputs.lowercase }}:${{ github.ref_name }}"
        build-args: |
          GITHUB_TOKEN=${{ secrets.GH_TOKEN }}