name: Deploy

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.13.15
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "useless-b1"
          heroku_email: ${{secrets.HEROKU_MAIL}}
          team: ${{secrets.HEROKU_TEAM}}
          docker_heroku_process_type: "worker"
          usedocker: true
          docker_build_args: |
            GITHUB_TOKEN
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}